site_name: Φάντασος Notes
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: teal
  language: zh
  icon:
    logo: material/pen
  favicon: src/img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
plugins:
  - glightbox
  - search:
      lang: jp
extra_javascript:
  - src/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - src/js/extra.js?v=16
  - src/js/math-csr.js?math-csr

copyright: Copyright &copy; Since 2022 Φάντασος ( <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"> CC BY-NC-SA 4.0 </a> & <a href="https://github.com/zTrix/sata-license"> SATA </a> )

nav: 
  - 首页: index.md
  - 数学: 
    - 选择性必修 第一册: 
      - 第一章 空间向量与立体几何: 
        - maths/book5/ch1/1.md
        - maths/book5/ch1/2.md
  - 物理: 
    - 选择性必修 第一册: 
      - 第一章 动量守恒定律:
        - 1.1 动量: physics/book4/ch1/1.md
        - 1.2 动量定理: physics/book4/ch1/2.md
        - 1.3 动量守恒定律: physics/book4/ch1/3.md
  - 生物: 
    - 必修1 分子与细胞: 
      - 第一章 走进细胞: 
        - 1.1 细胞是生命活动的基本单位: biology/book1/ch1/1.md
        - 1.2 细胞的多样性和统一性: biology/book1/ch1/2.md
      - 第二章 组成细胞的分子:
        - 2.1 细胞中的元素和化合物: biology/book1/ch2/1.md 
        - 2.2 细胞中的无机物: biology/book1/ch2/2.md
        - 2.3 细胞中的糖类和脂质: biology/book1/ch2/3.md 
        - 2.4 蛋白质是生命活动的主要承担者: biology/book1/ch2/4.md
        - 2.5 核酸是遗传信息的携带者: biology/book1/ch2/5.md 
      - 第三章 细胞的基本结构: 
        - 3.1 细胞膜的结构和功能: biology/book1/ch3/1.md
        - 3.2 细胞器之间的分工合作: biology/book1/ch3/2.md 
        - 3.3 细胞核的结构和功能: biology/book1/ch3/3.md
      - 第四章 细胞的物质输入和输出:
        - 4.1 被动运输: biology/book1/ch4/1.md
        - 4.2 主动运输和胞吞/胞吐: biology/book1/ch4/2.md
      - 第五章 细胞的能量供应和利用: 
        - 5.1 降低化学反应活化能的酶: biology/book1/ch5/1.md
        - 5.2 细胞的能量"货币"ATP: biology/book1/ch5/2.md
        - 5.3 细胞呼吸的原理和应用: biology/book1/ch5/3.md
        - 5.4 光合作用和能量转化: biology/book1/ch5/4.md
      - 第六章 细胞的生命历程: 
        - 6.1 细胞的增殖: biology/book1/ch6/1.md
        - 6.2 细胞的分化: biology/book1/ch6/2.md
        - 6.3 细胞的衰老和死亡: biology/book1/ch6/3.md
    - 选择性必修1 稳态与调节: 
      - 第一章 人体的内环境与稳态: 
        - 1.1 细胞生活的环境: biology/book3/ch1/1.md
        - 1.2 内环境的稳态: biology/book3/ch1/2.md
      - 第二章 神经调节:
        - 2.1 神经调节的结构基础: biology/book3/ch2/1.md
        - 2.2 神经调节的基本方式: biology/book3/ch2/2.md
        - 2.3 神经冲动的产生与传导: biology/book3/ch2/3.md
        - 2.4 神经系统的分级调节: biology/book3/ch2/4.md
        - 2.5 人脑的高级功能: biology/book3/ch2/5.md
      - 第三章 体液调节:
        - 3.1 激素与内分泌系统: biology/book3/ch3/1.md
        - 3.2 激素调节的过程: biology/book3/ch3/2.md
        - 3.3 体液调节与神经调节的关系: biology/book3/ch3/3.md
      - 第四章 免疫调节: 
        - 4.1 免疫系统的组成和功能: biology/book3/ch4/1.md
        - 4.2 特异性免疫: biology/book3/ch4/2.md